import { NextResponse } from "next/server";

export async function GET() {
  return NextResponse.json({
    menu: {
      subs: [
        {
          id: "sub001",
          name: "Paneer Tikka Sub",
          image: "https://i.ibb.co/R431BdCC/paneer-tikka-sub.png",
          description: "Spicy marinated paneer with crunchy veggies and sauces.",
          price: 399,
          type: "vegetarian",
          popularity: 90,
          protein_g: 22,
          spice_level: 3,
          prep_time_min: 6,
          customizations: {
            bread: ["White", "Whole Wheat", "Multigrain"],
            cheese: ["Cheddar", "Mozzarella", "None"],
            extras: ["Extra Veggies", "Extra Paneer", "No Onion"],
            sauces: ["Mint Mayo", "Chipotle Southwest", "Red Chili Sauce"],
          },
        },
        {
          id: "sub002",
          name: "Chicken Teriyaki Sub",
          image: "https://i.ibb.co/cS1JJH2n/chicken-teriyaki-sub.png",
          description: "Tender chicken in teriyaki sauce with fresh toppings.",
          price: 449,
          type: "non-vegetarian",
          popularity: 95,
          protein_g: 28,
          spice_level: 2,
          prep_time_min: 7,
          customizations: {
            bread: ["Italian Herbs & Cheese", "White", "Flatbread"],
            cheese: ["American", "Swiss", "None"],
            extras: ["Extra Chicken", "Avocado", "No Tomato"],
            sauces: ["Honey Mustard", "Sweet Onion", "BBQ"],
          },
        },
        {
          id: "sub003",
          name: "Mexican Aloo Patty Sub",
          image: "https://i.ibb.co/3yMBrLHn/mexican-aloo-patty-sub.png",
          description: "Crispy spiced potato patty with Mexican flavors.",
          price: 399,
          type: "vegetarian",
          popularity: 80,
          protein_g: 15,
          spice_level: 4,
          prep_time_min: 5,
          customizations: {
            bread: ["White", "Whole Wheat", "Flatbread"],
            cheese: ["Pepper Jack", "Cheddar", "None"],
            extras: ["Extra Patty", "Olives", "No Jalapeño"],
            sauces: ["Chipotle", "Schezwan", "Sweet Chili"],
          },
        },
      ],
      wraps: [
        {
          id: "wrap001",
          name: "Veggie Delight Wrap",
          image: "https://i.ibb.co/39gjHr8h/veggie-delight-wrap.png",
          description: "A wrap filled with crunchy fresh vegetables.",
          price: 299,
          type: "vegetarian",
          popularity: 85,
          protein_g: 10,
          spice_level: 1,
          prep_time_min: 4,
          customizations: {
            wrap_type: ["Spinach", "Tomato Basil", "Plain"],
            cheese: ["Cheddar", "None"],
            sauces: ["Ranch", "Honey Mustard", "Green Chilli"],
          },
        },
        {
          id: "wrap002",
          name: "Chicken Tandoori Wrap",
          image: "https://i.ibb.co/qG5dMrq/chicken-tandoori-wrap.png",
          description: "Tandoori-style chicken in a soft wrap.",
          price: 299,
          type: "non-vegetarian",
          popularity: 92,
          protein_g: 25,
          spice_level: 4,
          prep_time_min: 6,
          customizations: {
            wrap_type: ["Plain", "Whole Wheat"],
            cheese: ["Mozzarella", "None"],
            sauces: ["Tandoori Mayo", "Hot Sauce", "Mint Chutney"],
          },
        },
      ],
      beverages: [
        {
          id: "bev001",
          name: "Coca Cola",
          image: "https://i.ibb.co/xKkzK12B/coca-cola.png",
          description: "Classic Coke 500ml bottle.",
          price: 40,
          type: "beverage",
          popularity: 100,
          protein_g: 0,
          spice_level: 0,
          prep_time_min: 0,
          customizations: null,
        },
        {
          id: "bev002",
          name: "Bottled Water",
          image: "https://i.ibb.co/spQbk18b/bottled-water.png",
          description: "Mineral water, 500ml.",
          price: 20,
          type: "beverage",
          popularity: 60,
          protein_g: 0,
          spice_level: 0,
          prep_time_min: 0,
          customizations: null,
        },
      ],
    },
    sort_options: ["popularity", "protein_g", "spice_level", "prep_time_min"],
  });
}
